language: java
jdk:
  - oraclejdk8
before_script:  
 - "echo $JAVA_OPTS"
 - "export JAVA_OPTS=-Xmx512m"
install: JAVA_OPTS=-Xmx512m mvn install -DskipTests=true
branches:
 only:
  - master
  - /^fcrepo-*/
script:
 - mvn javadoc:jar
 - mvn javadoc:test-aggregate

notifications:
  irc: "irc.freenode.org#fcrepo"
  email:
      - ff-tech@googlegroups.com

